
export default {
  config: {
    locales: ['ru'],
    translations: {
      ru: {
        "page": "страница",
        "User": "Пользователь",
        "plugin::users-permissions.user": "Пользователь",
        "content-manager.containers.list.table-headers.status": "статус",
        "i18n.list-view.table.header.label": "доступен в",
        "search.placeholder": "поиск",
        "global.more.actions": "действия",
        "content-type-builder.search.placeholder": "поиск",
        "chat.tooltips.open-chat": "открыть чат",
        "chat.tooltips.close-chat": "закрыть чат",
        "chat.tooltips.create-chat": "создать чат",
        "chat.header.default-title": "новый чат",
        "chat.input.strapi-ai-can-make-errors": "ИИ может совершать ошибки",
        "api::page.page": "страница",
        "about": "информавция о",
        "about.about": "информавция о",
        "contacts": "контакты",
        "contacts.contacts": "контакты",
        "contacts.form": "форма",
        "footer": "футер",
        "footer.contacts": "контаты",
        "footer.footer": "футер",
        "footer.nav": "меню",
        "header": "шапка",
        "header.header": "шапка",
        "header.navigation": "меню",
        "investors": "инвесторы",
        "investors.investors": "инвесторы",
        "investors.list": "список",
        "mission": "миссия",
        "mission.items": "элементы миссий",
        "mission.mission": "миссия",
        "news": "новости",
        "news.items": "элементы новостей",
        "news.news": "новости",
        "partners": "партнеры",
        "partners.partners": "партнеры",
        "plans": "планы",
        "plans.plans": "планы",
        "projects": "проекты",
        "projects.images": "изображения",
        "projects.projects": "проекты",
        "promo": "промо",
        "promo.promotion": "промо",
        "promo-statistics": "статистика",
        "promo-statistics.statistics": "статистика",
        "promo-statistics.stats-item": "элементы статистики",
        "values": "ценности",
        "values.values": "ценности",
        "app.utils.drag": "тащить",
        "app.utils.toggle": "переключить",
        "content-manager.content-types.api::page.page.id": "id",
        "content-manager.content-types.api::page.page.createdAt": "создан",
        "content-manager.content-types.api::page.page.updatedAt": "обновлен",
        "content-manager.content-types.api::page.page.header": "шапка",
        "content-manager.content-types.api::page.page.promo": "промо",
        "content-manager.content-types.api::page.page.about": "информация о",
        "content-manager.content-types.api::page.page.plans": "планы",
        "content-manager.content-types.api::page.page.mission": "миссия",
        "content-manager.content-types.api::page.page.values": "ценности",
        "content-manager.content-types.api::page.page.projects": "проекты",
        "content-manager.content-types.api::page.page.investors": "инвесторы",
        "content-manager.content-types.api::page.page.news": "новости",
        "content-manager.content-types.api::page.page.partners": "партнеры",
        "content-manager.content-types.api::page.page.contacts": "контакты",
        "content-manager.content-types.api::page.page.footer": "футер",
        "content-manager.components.header.header.nav": "меню",
        "content-manager.components.header.navigation.about": "информация о",
        "content-manager.components.header.navigation.projects": "проекты",
        "content-manager.components.header.navigation.investors": "инвесторы",
        "content-manager.components.header.navigation.news": "новости",
        "content-manager.components.header.navigation.partners": "партнеры",
        "content-manager.components.header.navigation.contacts": "контакты",
        "content-manager.components.promo.promotion.title": "заголовок",
        "content-manager.components.promo.promotion.subtitle": "подзаголовок",
        "content-manager.components.promo.promotion.button": "кнопка",
        "content-manager.components.promo.promotion.stats": "статистика",
        "content-manager.components.promo-statistics.statistics.stats_items": "элементы статистики",
        "content-manager.components.promo-statistics.stats-item.value": "значение элемента ститистики",
        "content-manager.components.promo-statistics.stats-item.label": "имя элемента ститистики",
        "content-manager.components.about.about.label": "название",
        "content-manager.components.about.about.title": "заголовок",
        "content-manager.components.about.about.subtitle": "подзаголовок",
        "content-manager.components.about.about.video": "видео",
        "content-manager.components.about.about.video_bg": "фоновое видео",
        "content-manager.components.plans.plans.title": "заголовок",
        "content-manager.components.plans.plans.image": "изображение",
        "content-manager.components.mission.mission.label": "название",
        "content-manager.components.mission.mission.title": "заголовок",
        "content-manager.components.mission.mission.items": "элементы миссий",
        "content-manager.components.mission.items.title": "заголовок",
        "content-manager.components.mission.items.text": "текст",
        "content-manager.components.values.values.label": "название",
        "content-manager.components.values.values.title": "заголовок",
        "content-manager.components.values.values.subtitle": "подзаголовок",
        "content-manager.components.projects.projects.title": "заголовок",
        "content-manager.components.projects.projects.text": "текст",
        "content-manager.components.projects.projects.images": "изображения",
        "content-manager.components.projects.images.image": "изображение",
        "content-manager.components.investors.investors.label": "название",
        "content-manager.components.investors.investors.title": "заголовок",
        "content-manager.components.investors.investors.text": "текст",
        "content-manager.components.investors.investors.list": "список",
        "content-manager.components.investors.investors.button": "кнопка",
        "content-manager.components.investors.investors.video": "видео",
        "content-manager.components.investors.list.value": "значение",
        "content-manager.components.news.news.title": "заголовок",
        "content-manager.components.news.news.items": "элементы новостей",
        "content-manager.components.news.items.title": "заголовок",
        "content-manager.components.news.items.subtitle": "подзаголовок",
        "content-manager.components.news.items.date": "дата",
        "content-manager.components.news.items.linkedin": "linkedin",
        "content-manager.components.news.items.image": "изображение",
        "content-manager.components.partners.partners.label": "партнеры",
        "content-manager.components.partners.partners.title": "заголовок",
        "content-manager.components.contacts.contacts.label": "название",
        "content-manager.components.contacts.contacts.title": "заголовок",
        "content-manager.components.contacts.contacts.form": "форма",
        "content-manager.components.contacts.form.text": "текст",
        "content-manager.components.contacts.form.button": "кнопка",
        "content-manager.components.contacts.form.privacy": "privacy policy",
        "content-manager.components.contacts.form.privacyBold": "жирный privacy",
        "content-manager.components.contacts.form.namePlaceholder": "placeholder имя",
        "content-manager.components.contacts.form.emailPlaceholder": "placeholder имейл",
        "content-manager.components.contacts.form.messagePlaceholder": "placeholder сообщение",
        "content-manager.components.footer.footer.nav": "меню",
        "content-manager.components.footer.footer.contacts": "контакты",
        "content-manager.components.footer.footer.copyright": "права (copyright)",
        "content-manager.components.footer.nav.value": "значение",
        "content-manager.components.footer.contacts.title": "заголовок",
        "content-manager.components.footer.contacts.phone": "телефон",
        "content-manager.components.footer.contacts.phoneValue": "телефон value",
        "content-manager.components.footer.contacts.email": "имейл",
        "content-manager.components.footer.contacts.emailValue": "имейл value",
        "content-manager.content-types.plugin::users-permissions.user.id": "id",
        "content-manager.content-types.plugin::users-permissions.user.username": "имя пользователя",
        "content-manager.content-types.plugin::users-permissions.user.email": "имейл",
        "content-manager.content-types.plugin::users-permissions.user.confirmed": "подтвержден",
        "content-manager.content-types.plugin::users-permissions.user.password": "пароль",
        "content-manager.content-types.plugin::users-permissions.user.blocked": "заблокирован",
        "content-manager.content-types.plugin::users-permissions.user.role": "роль",
        "content-manager.form.Input.hint.character.unit": "character",
      },
    }
  },
  bootstrap(app) {
    console.log(app);
  },
};
